# .github/workflows/generate_newsletter.yml
name: Generate Newsletter

permissions:
  contents: write   # allow pushing generated reports and index.html

on:
  schedule:
    - cron: '0 8 * * *'    # every day at 07:00 UTC
  workflow_dispatch:      # manual trigger via Actions UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate newsletter (and update index.html)
        run: |
          python main.py

      - name: Commit & push reports and index
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add docs/outputs/ docs/index.html
          # only commit if there are changes
          git diff --cached --quiet || git commit -m "chore: daily newsletter reports [skip ci]"
          git push origin main
