# .github/workflows/send_newsletter.yml
name: Send Newsletter

on:
  workflow_dispatch:           # allow manual runs
  workflow_run:
    workflows: ["Generate Newsletter"]
    types:
      - completed             # auto‑trigger after Generate Newsletter succeeds

permissions:
  contents: read

jobs:
  send:
    runs-on: ubuntu-latest

    # RUN if
    #  • manually dispatched  OR
    #  • triggered by Generate Newsletter AND it succeeded
    if: ${{ 
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') 
      }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Send Newsletter Emails
        env:
          SENDER_EMAIL:         ${{ secrets.SENDER_EMAIL }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        run: python - m financial_newsletter.utils.send_email_gmail
