name: Sync Subscribers from MailerLite

# Grant the workflow write access to repo contents
permissions:
  contents: write

# Trigger daily at 2 AM UTC or manually
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  sync-subscribers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (main branch)
        uses: actions/checkout@v3
        with:
          # ensure you have the full history so rebase works
          fetch-depth: 0
          # make sure you're on main, not a detached HEAD
          ref: main
          # allow pushing back to the repo
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-dotenv requests

      - name: Fetch and update subscribers.csv
        env:
          MAILERLITE_API_KEY: ${{ secrets.MAILERLITE_API_KEY }}
        run: |
          python update_subscribers.py

      - name: Commit and push updated subscribers.csv
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add subscribers.csv
          if ! git diff --cached --quiet; then
            git commit -m "chore: update subscribers.csv [skip ci]"
          fi
          # Make sure to rebase onto the latest remote main
          git pull --rebase origin main
          git push
