name: Sync Subscribers from MailerLite

permissions:
  contents: write

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  sync-subscribers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (main branch)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-dotenv requests

      - name: Fetch and update subscribers.csv
        env:
          MAILERLITE_API_KEY: ${{ secrets.MAILERLITE_API_KEY }}
        run: |
          python update_subscribers.py

      - name: Commit and push updated subscribers.csv
        run: |
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
        
            # Fetch the LATEST changes FIRST
            git fetch origin main
        
            # Rebase local changes on top of the latest remote changes
            git rebase origin/main
        
            # Add/commit changes AFTER ensuring local is up-to-date
            git add subscribers.csv
            if ! git diff --cached --quiet; then
              git commit -m "chore: update subscribers.csv [skip ci]"
            fi
        
            # Push with --force-with-lease to handle edge cases
            git push --force-with-lease